// Generated by CoffeeScript 1.6.1
(function() {
  var Exo, Node, StateMachine;

  Exo = this.Exo = {};

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Exo;
  }

  StateMachine = (function() {

    StateMachine.E_DUPLICATE_STATE = "E_DUPLICATE_STATE: States must be distinct";

    StateMachine.E_DUPLICATE_TRANSITION = "E_DUPLICATE_TRANSITION: Transitions must be distinct";

    StateMachine.E_UNDEFINED_STATE = "E_UNDEFINED_STATE: All states used in transitions must be defined in the states array";

    function StateMachine(opts) {
      var currentState, currentTransition, initialState, states, transitions, validate;
      if (opts == null) {
        opts = {};
      }
      states = opts.states || [];
      transitions = opts.transitions || [];
      (validate = function() {
        var sCheck, tCheck, tStates, transition, unique;
        unique = function(a) {
          var key, output, value, _i, _ref, _results;
          output = {};
          for (key = _i = 0, _ref = a.length; 0 <= _ref ? _i < _ref : _i > _ref; key = 0 <= _ref ? ++_i : --_i) {
            output[a[key]] = a[key];
          }
          _results = [];
          for (key in output) {
            value = output[key];
            _results.push(value);
          }
          return _results;
        };
        if (states.length !== unique(states).length) {
          throw StateMachine.E_DUPLICATE_STATE;
        }
        tCheck = [];
        sCheck = [];
        for (transition in transitions) {
          tStates = transitions[transition];
          tCheck.push("" + tStates.from + "->" + tStates.to);
          sCheck.push(tStates.to);
          sCheck.push(tStates.from);
        }
        if (unique(sCheck).length > states.length) {
          throw StateMachine.E_UNDEFINED_STATE;
        }
        if (tCheck.length !== unique(tCheck).length) {
          throw StateMachine.E_DUPLICATE_TRANSITION;
        }
      })();
      currentState = initialState = opts.initialState || null;
      currentTransition = null;
      this.attemptTransition = function(transitionName) {
        if (!this.isTransitioning() && this.transitionIsPossible(transitionName)) {
          currentTransition = transitions[transitionName];
          this.performTransition(transitionName);
          return true;
        } else {
          return false;
        }
      };
      this.isTransitioning = function() {
        return currentTransition !== null;
      };
      this.transitionIsPossible = function(transitionName) {
        var transition;
        if (transition = transitions[transitionName]) {
          return currentState !== transition.to && currentState === transition.from;
        } else {
          return false;
        }
      };
      this.onTransitionComplete = function() {
        if (currentTransition) {
          currentState = currentTransition.to;
          currentTransition = null;
          return true;
        } else {
          return false;
        }
      };
      this.states = function() {
        return states;
      };
      this.transitions = function() {
        return transitions;
      };
      this.currentState = function() {
        return currentState;
      };
      this.initialState = function() {
        return initialState;
      };
    }

    StateMachine.prototype.performTransition = function(transitionName) {};

    return StateMachine;

  })();

  Exo.StateMachine = StateMachine;

  /* 
  Overview of a node
  
  The Class Methods are used internally by the framework.
  */


  Node = (function() {

    Node.__currentId = 0;

    Node.Transitions = {
      ACTIVATE: 'activate',
      DEACTIVATE: 'deactivate'
    };

    Node.States = {
      ACTIVATED: 'activated',
      DEACTIVATED: 'deactivated'
    };

    Node.Modes = {
      EXCLUSIVE: 'exclusive',
      MULTI: 'multi'
    };

    /* 
    Generate the next unique node ID string.
    */


    Node.nextId = function() {
      Node.__currentId = Node.__currentId + 1;
      return Node.__currentId;
    };

    /* 
    Attempt to activate a node instance.
    @param [Node] node
    */


    Node.activate = function(node) {
      var parent, sibling;
      if (this.lineageIsBusy(node) || node.isActivated()) {
        return false;
      }
      if (parent = node.parent()) {
        if (parent.isActivated()) {
          if (parent.mode() === Node.Modes.EXCLUSIVE) {
            if (sibling = parent.activatedChildren()[0]) {
              sibling.setOnDeactivatedAction({
                node: node,
                transition: Node.Transitions.ACTIVATE
              });
              return Node.deactivate(sibling);
            }
          }
        } else {
          if (!parent.childrenCanActivate()) {
            return false;
          }
          parent.setOnActivatedAction({
            node: node,
            transition: Node.Transitions.ACTIVATE
          });
          return Node.activate(parent);
        }
      }
      return node.attemptTransition(Node.Transitions.ACTIVATE);
    };

    /* 
    Attempt to deactivate a node instance.
    @param [Node] node
    */


    Node.deactivate = function(node) {
      var child, _i, _len, _ref;
      if (node.isActivated() && !this.lineageIsBusy(node)) {
        if (node.mode() === Node.Modes.EXCLUSIVE) {
          if (child = node.activatedChildren()[0]) {
            child.setOnDeactivatedAction({
              node: node,
              transition: Node.Transitions.DEACTIVATE
            });
            return Node.deactivate(child);
          }
        } else if (node.mode === Node.Modes.MULTI) {
          _ref = node.activatedChildren();
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            child = _ref[_i];
            Node.deactivate(child);
          }
        }
        node.attemptTransition(Node.Transitions.DEACTIVATE);
      }
      return false;
    };

    /* 
    Attempts to perform activation if the node is deactivated and vice versa.
    @param [Node] node
    */


    Node.toggle = function(node) {
      if (node.isActivated()) {
        return this.deactivate(node);
      } else {
        return this.activate(node);
      }
    };

    /* 
    Find out if the lineage of a node is busy. This will be true if a parent, sibling or child is currently transitioning.
    @param [Node] node
    */


    Node.lineageIsBusy = function(node) {
      var parent;
      if (parent = node.parent()) {
        if (parent.isBusy()) {
          return true;
        }
        while (parent = parent.parent()) {
          if (parent.isBusy()) {
            return true;
          }
        }
      }
      return false;
    };

    /* 
    Node instances call this function when done activating. If there is a pending action it will be executed.
    @param [Node] node
    */


    Node.onNodeActivated = function(node) {
      var action;
      if (node.parent()) {
        node.parent().onChildActivated(node);
      }
      if (action = node.onActivatedAction()) {
        return this.processAction(action);
      }
    };

    /* 
    Node instances call this function when done deactivating. If there is a pending action it will be executed.
    @param [Node] node
    */


    Node.onNodeDeactivated = function(node) {
      var action, _ref;
      if (node.parent()) {
        node.parent().onChildDeactivated(node);
      }
      if (action = node.onDeactivatedAction()) {
        return this.processAction(action);
      } else if ((_ref = node.parent()) != null ? _ref.defaultChild() : void 0) {
        return Node.activate(node.parent().defaultChild());
      }
    };

    /* 
    Process an action of activating or deactivating a node reference.
    @param [Object] action
    */


    Node.processAction = function(action) {
      if (action.transition === Node.Transitions.ACTIVATE) {
        return this.activate(action.node);
      } else if (action.transition === Node.Transitions.DEACTIVATE) {
        return this.deactivate(action.node);
      }
    };

    /* 
    Constructor
    @param [Object] options
    @option options [Array] children add children at instantiation.
    */


    function Node(opts) {
      var child, node, _i, _j, _len, _len1, _ref, _ref1;
      if (opts == null) {
        opts = {};
      }
      this._parent = null;
      this._childMap = {};
      this._defaultChild = null;
      this._nId = "exo#" + (Node.nextId());
      if (opts.children) {
        _ref = opts.children;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          node = _ref[_i];
          node.setParent(this);
          _ref1 = opts.children;
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            child = _ref1[_j];
            this.addChild(child);
          }
        }
      }
      this._mode = opts.mode || (opts.mode = Node.Modes.EXCLUSIVE);
      this._initialState = opts.initialState || (opts.initialState = Node.States.DEACTIVATED);
      if (opts.childrenCanActivate === false) {
        this._childrenCanActivate = false;
      } else {
        this._childrenCanActivate = true;
      }
      this._onActivatedAction = null;
      this._onDeactivatedAction = null;
    }

    Node.prototype.nodeId = function() {
      return this._nId;
    };

    Node.prototype.setNodeId = function(nid) {
      var _ref;
      if ((_ref = this._parent) != null) {
        _ref.onChildIdUpdated(this._nId, nid, this);
      }
      return this._nId = nid;
    };

    Node.prototype.sm = function() {
      var _this = this;
      if (this._smRef) {
        return this._smRef;
      }
      this._smRef = new Exo.StateMachine({
        states: [Node.States.DEACTIVATED, Node.States.ACTIVATED],
        initialState: this._initialState,
        transitions: {
          activate: {
            from: Node.States.DEACTIVATED,
            to: Node.States.ACTIVATED
          },
          deactivate: {
            from: Node.States.ACTIVATED,
            to: Node.States.DEACTIVATED
          }
        }
      });
      this._smRef.performTransition = function(t) {
        if (t === Node.Transitions.ACTIVATE) {
          _this.beforeActivate();
          return _this.doActivate();
        } else if (t === Node.Transitions.DEACTIVATE) {
          _this.beforeDeactivate();
          return _this.doDeactivate();
        }
      };
      return this._smRef;
    };

    Node.prototype.onChildIdUpdated = function(oldId, newId, child) {
      delete this._childMap[oldId];
      return this._childMap[newId] = child;
    };

    Node.prototype.setOnActivatedAction = function(action) {
      return this._onActivatedAction = action;
    };

    Node.prototype.onActivatedAction = function() {
      return this._onActivatedAction;
    };

    Node.prototype.setOnDeactivatedAction = function(action) {
      return this._onDeactivatedAction = action;
    };

    Node.prototype.onDeactivatedAction = function() {
      return this._onDeactivatedAction;
    };

    Node.prototype.childrenCanActivate = function() {
      return this._childrenCanActivate;
    };

    Node.prototype.setMode = function(m) {
      return this._mode = m;
    };

    Node.prototype.mode = function() {
      return this._mode;
    };

    Node.prototype.setParent = function(node) {
      return this._parent = node;
    };

    Node.prototype.parent = function() {
      return this._parent;
    };

    Node.prototype.childrenAsArray = function(obj) {
      var arr, child, id, _ref;
      arr = [];
      _ref = this._childMap;
      for (id in _ref) {
        child = _ref[id];
        arr.push(child);
      }
      return arr;
    };

    Node.prototype.addChild = function(node) {
      if (node === null || typeof node === 'undefined') {
        throw new Error("ExoReferenceError -> addChild: " + node + " is not a valid Exo.Node");
      }
      if (this.nodeId() === node.nodeId()) {
        throw new Error("ExoReferenceError -> An Exo.Node instance can't pass itself to addChild");
      }
      node.setParent(this);
      return this._childMap[node.nodeId()] = node;
    };

    Node.prototype.removeChild = function(node) {
      return delete this._childMap[node.nodeId()];
    };

    Node.prototype.setDefaultChild = function(node) {
      return this._defaultChild = node;
    };

    Node.prototype.defaultChild = function() {
      return this._defaultChild;
    };

    Node.prototype.children = function() {
      return this.childrenAsArray();
    };

    Node.prototype.activatedChildren = function() {
      return this.children().filter(function(n) {
        return n.isActivated();
      });
    };

    Node.prototype.childById = function(id) {
      return this._childMap[id];
    };

    Node.prototype.descendantById = function(id) {
      var child, descendant, _i, _len, _ref;
      child = this.childById(id);
      if (child) {
        return child;
      }
      _ref = this.children();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        child = _ref[_i];
        descendant = child.getDescendantById(id);
        if (descendant) {
          return descendant;
        }
      }
    };

    Node.prototype.siblings = function() {
      var ownId;
      ownId = this.nodeId();
      if (this.parent()) {
        return this.parent().children().filter(function(n) {
          return n.nodeId() !== ownId;
        });
      }
      return [];
    };

    Node.prototype.isActivated = function() {
      return this.sm().currentState() === Node.States.ACTIVATED;
    };

    Node.prototype.isTransitioning = function() {
      return this.sm().isTransitioning();
    };

    Node.prototype.isBusy = function() {
      if (this.isTransitioning()) {
        return true;
      }
      if (this.mode() === Node.Modes.EXCLUSIVE) {
        if (this.children().filter(function(n) {
          return n.isBusy();
        }).length > 0) {
          return true;
        }
      }
      return false;
    };

    Node.prototype.haveBusyChildren = function() {
      return this.children().filter(function(n) {
        return n.isBusy();
      }).length > 0;
    };

    Node.prototype.attemptTransition = function(t) {
      return this.sm().attemptTransition(t);
    };

    Node.prototype.activate = function() {
      return Node.activate(this);
    };

    Node.prototype.deactivate = function() {
      return Node.deactivate(this);
    };

    Node.prototype.toggle = function() {
      return Node.toggle(this);
    };

    Node.prototype.deactivateChildren = function() {
      var child, _i, _len, _ref, _results;
      _ref = this.children();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        child = _ref[_i];
        _results.push(child.deactivate());
      }
      return _results;
    };

    Node.prototype.onActivated = function() {
      this.sm().onTransitionComplete();
      Node.onNodeActivated(this);
      return this.setOnActivatedAction(null);
    };

    Node.prototype.onDeactivated = function() {
      this.sm().onTransitionComplete();
      Node.onNodeDeactivated(this);
      return this.setOnDeactivatedAction(null);
    };

    Node.prototype.beforeActivate = function() {};

    Node.prototype.doActivate = function() {
      return this.onActivated();
    };

    Node.prototype.beforeDeactivate = function() {};

    Node.prototype.doDeactivate = function() {
      return this.onDeactivated();
    };

    Node.prototype.onChildActivated = function(child) {};

    Node.prototype.onChildDeactivated = function(child) {};

    return Node;

  })();

  Exo.Node = Node;

}).call(this);
