// Generated by CoffeeScript 1.6.1
(function() {
  var Controller, List, Model, Spine,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    __slice = [].slice;

  Spine = this.Spine || require('spine');

  Controller = (function(_super) {

    __extends(Controller, _super);

    function Controller(opts) {
      var nodeOpts, _node,
        _this = this;
      if (opts == null) {
        opts = {};
      }
      nodeOpts = opts;
      _node = null;
      this.node = function() {
        if (!_node) {
          _node = new Exo.Node(nodeOpts);
          _node.controller = this;
        }
        return _node;
      };
      this.nodeId = function() {
        return this.node().nodeId();
      };
      this.setNodeId = function(id) {
        return this.node().setNodeId(id);
      };
      this.setMode = function(mode) {
        return this.node().setMode(mode);
      };
      this.activate = function() {
        return this.node().activate();
      };
      this.deactivate = function() {
        return this.node().deactivate();
      };
      this.toggle = function() {
        return this.node().toggle();
      };
      this.node().beforeActivate = function() {
        var _ref;
        _this.trigger('beforeActivate', _this);
        return (_ref = _this.beforeActivate) != null ? _ref.call(_this) : void 0;
      };
      this.node().doActivate = function() {
        return _this.doActivate();
      };
      this.node().beforeDeactivate = function() {
        var _ref;
        _this.trigger('beforeDeactivate', _this);
        return (_ref = _this.beforeDeactivate) != null ? _ref.call(_this) : void 0;
      };
      this.node().doDeactivate = function() {
        return _this.doDeactivate();
      };
      this.node().onChildActivated = function(node) {
        _this.trigger('onChildActivated', node.controller);
        return typeof _this.onChildActivated === "function" ? _this.onChildActivated(node.controller) : void 0;
      };
      this.node().onChildDeactivated = function(node) {
        _this.trigger('onChildDeactivated', node.controller);
        return typeof _this.onChildDeactivated === "function" ? _this.onChildDeactivated(node.controller) : void 0;
      };
      this.addChild = function(controller) {
        return this.node().addChild(controller != null ? controller.node() : void 0);
      };
      this.children = function() {
        return this.node().children().map(function(node) {
          return node.controller;
        });
      };
      this.parent = function() {
        var _ref;
        return (_ref = this.node().parent()) != null ? _ref.controller : void 0;
      };
      this.childById = function(id) {
        var _ref;
        return (_ref = this.node().childById(id)) != null ? _ref.controller : void 0;
      };
      this.descendantById = function(id) {
        var _ref;
        return (_ref = this.node().descendantById(id)) != null ? _ref.controller : void 0;
      };
      this.siblings = function() {
        return this.node().siblings().map(function(node) {
          return node.controller;
        });
      };
      this.activatedChildren = function() {
        return this.node().activatedChildren();
      };
      this.removeChild = function(controller) {
        return this.node().removeChild(controller.node());
      };
      this.setDefaultChild = function(controller) {
        return this.node().setDefaultChild(controller.node());
      };
      this.defaultChild = function() {
        return this.node().defaultChild();
      };
      this.isActivated = function() {
        return this.node().isActivated();
      };
      this.isTransitioning = function() {
        return this.node().isTransitioning();
      };
      this.isBusy = function() {
        return this.node().isBusy();
      };
      this.haveBusyChildren = function() {
        return this.node().haveBusyChildren();
      };
      if (opts.initialState) {
        delete opts.initialState;
      }
      if (opts.mode) {
        delete opts.mode;
      }
      if (opts.children) {
        delete opts.children;
      }
      Controller.__super__.constructor.call(this, opts);
      this.prepare();
    }

    Controller.prototype.prepare = function() {};

    Controller.prototype.doActivate = function() {
      return this.onActivated();
    };

    Controller.prototype.onActivated = function() {
      this.node().onActivated();
      return this.trigger('onActivated', this);
    };

    Controller.prototype.doDeactivate = function() {
      return this.onDeactivated();
    };

    Controller.prototype.onDeactivated = function() {
      this.node().onDeactivated();
      return this.trigger('onDeactivated', this);
    };

    return Controller;

  })(Spine.Controller);

  Exo.Spine || (Exo.Spine = {});

  Exo.Spine.Controller = Controller;

  List = (function(_super) {

    __extends(List, _super);

    function List(opts) {
      if (opts == null) {
        opts = {};
      }
      opts.initialState || (opts.initialState = Exo.Node.States.ACTIVATED);
      opts.mode || (opts.mode = Exo.Node.Modes.MULTI);
      List.__super__.constructor.call(this, opts);
    }

    List.prototype.templateFor = function(templates, item) {
      return templates[item.className];
    };

    List.prototype.controllerFor = function(controllers, item) {
      return controllers[item.className];
    };

    List.prototype.render = function(collection, opts) {
      if (opts == null) {
        opts = {};
      }
      this.collection = collection;
      if (this.template || this.templates) {
        return this.renderTemplates(collection);
      } else if (this.controller || this.controllers) {
        return this.renderControllers(collection, opts);
      }
    };

    List.prototype.renderTemplates = function(collection) {
      var el, html, item, templates, _i, _len, _results;
      templates = this.templates || {
        "default": this.template
      };
      _results = [];
      for (_i = 0, _len = collection.length; _i < _len; _i++) {
        item = collection[_i];
        html = (templates["default"] || templates[item.constructor.className]).call(this, item);
        el = $(html).appendTo(this.el);
        _results.push($(el).data('item', item));
      }
      return _results;
    };

    List.prototype.renderControllers = function(collection, opts) {
      var child, controllers, i, item, _i, _len;
      controllers = this.controllers || {
        "default": this.controller
      };
      this.deactivateAndKillOrphans(this.children(), collection);
      for (i = _i = 0, _len = collection.length; _i < _len; i = ++_i) {
        item = collection[i];
        child = this.getOrCreateChild(item, controllers[item.constructor.className] || controllers["default"], opts);
        child.listIndex = i;
        if (child.moveTo) {
          child.moveTo(i);
        }
        child.activate();
      }
      return this.trigger('afterRender', this);
    };

    List.prototype.getOrCreateChild = function(item, controller, opts) {
      var child;
      child = this.childById(item.constructor.className + item.id);
      if (!child) {
        child = new controller(opts);
        this.addChild(child);
        child.setNodeId(item.constructor.className + item.id);
        child.prepareWithModel(item);
        this.append(child);
        $(child.el).data('item', item);
      }
      return child;
    };

    List.prototype.deactivateAndKillOrphans = function(children, collection) {
      var orphan, orphans, _i, _len, _results,
        _this = this;
      orphans = children.filter(function(child) {
        var _ref;
        return _ref = child.nodeId(), __indexOf.call(collection.map(function(item) {
          return item.constructor.className + item.id;
        }), _ref) < 0;
      });
      _results = [];
      for (_i = 0, _len = orphans.length; _i < _len; _i++) {
        orphan = orphans[_i];
        if (orphan.isActivated() && !orphan.isBusy()) {
          orphan.bind('onDeactivated', function(controller) {
            _this.removeChild(controller);
            return controller.release();
          });
        }
        _results.push(orphan.deactivate());
      }
      return _results;
    };

    List.prototype.click = function(e) {
      var item;
      if ($(e.currentTarget).item) {
        item = $(e.currentTarget).item();
      } else {
        item = $(e.currentTarget).data('item');
      }
      this.trigger('select', item, $(e.currentTarget));
      return true;
    };

    return List;

  })(Exo.Spine.Controller);

  if (typeof Exo !== "undefined" && Exo !== null) {
    Exo.Spine || (Exo.Spine = {});
  }

  if (typeof Exo !== "undefined" && Exo !== null) {
    Exo.Spine.List = List;
  }

  if (typeof module !== "undefined" && module !== null) {
    module.exports = List;
  }

  Spine = this.Spine || require('spine');

  Model = (function(_super) {

    __extends(Model, _super);

    function Model() {
      return Model.__super__.constructor.apply(this, arguments);
    }

    Model.defaults = function(atts) {
      return this.defaultValues = atts;
    };

    Model.configure = function() {
      var attributes, name;
      name = arguments[0], attributes = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      attributes = attributes.concat(['created_at', 'updated_at']);
      return Model.__super__.constructor.configure.apply(this, [name].concat(__slice.call(attributes)));
    };

    Model.create = function(atts, options) {
      var attribute, _i, _len, _ref;
      if (atts == null) {
        atts = {};
      }
      if (options == null) {
        options = {};
      }
      if (this.defaultValues) {
        _ref = this.attributes;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          attribute = _ref[_i];
          if (!atts[attribute]) {
            if (this.defaultValues[attribute.toString()] || this.defaultValues[attribute.toString()] === 0) {
              atts[attribute.toString()] = this.defaultValues[attribute.toString()];
            }
          }
        }
      }
      return Model.__super__.constructor.create.call(this, atts, options);
    };

    Model.prototype.getClassName = function() {
      return this.constructor.className;
    };

    return Model;

  })(Spine.Model);

  if (typeof Exo !== "undefined" && Exo !== null) {
    Exo.Spine || (Exo.Spine = {});
  }

  if (typeof Exo !== "undefined" && Exo !== null) {
    Exo.Spine.Model = Model;
  }

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Model;
  }

}).call(this);
